apiVersion: v1
kind: Service
Metadata:
  name: nginx-service
  namespace: k8s-practice
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
  - name: main
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: sidecar
    port: 8080
    targePort: 8080
    nodePort: 30081
